name: CI Pipeline

on:
  pull_request:
    branches:
      - "main"
    paths:
      - "**.c"
      - "**.h"
      - "**.cpp"
      - "**.hpp"
      - "**.py"
      - "**.pyx"  # Added for Cython files
      - "**.build"

permissions:
  contents: read

jobs:
  host_macosx:
    strategy:
      matrix:
        os: [10.15, 11, 12, 13]  # macOS versions
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup Python and Tools
      run: |
          python -m pip install meson==1.0.0 ninja==1.11.1 cython==3.0.8
    - name: Setup Build Directory
      run: |
          meson setup builddir -Dwith_test=enabled
    - name: Compile Source Code
      run: |
          meson compile -C builddir
    - name: Test Project Code
      run: |
        meson test -C builddir -v --test-args='--mode devops'

  host_windows:
    strategy:
      matrix:
        os: ['windows-latest', 'windows-2022']
        mingw: [false, 'mingw32', 'mingw64', 'MSYS']
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4
    - name: Setup Python and Tools
      run: |
          python -m pip install meson==1.0.0 ninja==1.11.1 cython==3.0.8
    - name: Setup MinGW/MSYS
      if: matrix.mingw != false
      uses: msys2/setup-msys2@v2
      with:
        msystem: ${{ matrix.mingw }}
        update: true
    - name: Setup Build Directory
      run: |
          meson setup builddir -Dwith_test=enabled
    - name: Compile Source Code
      run: |
          meson compile -C builddir
    - name: Test Project Code
      run: |
          meson test -C builddir -v --test-args='--mode devops'

  host_ubuntu:
    strategy:
      matrix:
        ubuntu_version: ['latest', '22.04']
    runs-on: ubuntu-${{ matrix.ubuntu_version }}
    steps:
    - uses: actions/checkout@v4
    - name: Setup Python and Tools
      run: |
          python -m pip install meson==1.0.0 ninja==1.11.1 cython==3.0.8
          sudo apt-get install -y gcc
    - name: Setup Build Directory
      run: |
          meson setup builddir -Dwith_test=enabled
    - name: Compile Source Code
      run: |
          meson compile -C builddir
    - name: Test Project Code
      run: |
          meson test -C builddir -v --test-args='--mode devops'

  meson_support:
    strategy:
      matrix:
        meson_version: ['1.0.0', '1.1.0', '1.2.0', '1.3.0']
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup Python and Tools
      run: |
          python -m pip install meson==${{ matrix.meson_version }} ninja==1.11.1 cython==3.0.8
    - name: Setup Build Directory
      run: |
          meson setup builddir -Dwith_test=enabled
    - name: Compile Source Code
      run: |
          meson compile -C builddir
    - name: Test Project Code
      run: |
          meson test -C builddir -v --test-args='--mode devops'
